- name: Deploy files
  copy:
    src: '{{ playbook_dir }}/../../dw/{{ item }}'
    dest: "{{ app_directory }}/dw/"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'
  loop:
    - '.env'
    
