# todo build and host images
- name: Deploy directories
  synchronize:
    delete: true
    src: '{{ playbook_dir }}/../docker/{{ item }}'
    dest: "{{ app_directory }}/docker/"
    recursive: true
    rsync_opts:
      - "--chown={{ maintainer_user }}:{{ maintainer_user }}"
      - '--chmod=0755'
      - '--exclude=db'
  loop:
    - 'backend'
    - 'mariadb'
    - 'dw'

- name: Create .env and docker-compose.yml
  template:
    src: "templates/{{ item }}.j2"
    dest: "/{{ app_directory }}/docker/{{ item }}"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'
  loop:
    - '.env'
    - 'docker-compose.yml'

- name: Deploy files
  copy:
    src: '{{ playbook_dir }}/../docker/{{ item }}'
    dest: "{{ app_directory }}/docker/"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'
  loop:
    - '.dockerignore'

- name: Docker compose up
  docker_compose:
    project_src: "{{ app_directory }}/docker"
    state: present
    build: true
