- name: Docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ app_directory }}/docker"
    state: present
    build: always

- name: Composer install
  shell:
    cmd: docker compose exec -T backend bash -l -c "composer install --no-dev --optimize-autoloader --no-interaction"
    chdir: "{{ app_directory }}/docker"

- name: Symfony cache clear
  shell:
    cmd: docker compose exec -T backend bash -l -c "php bin/console cache:clear --no-interaction"
    chdir: "{{ app_directory }}/docker"

- name: Doctrine migration
  shell:
    cmd: docker compose exec -T backend bash -l -c "php bin/console doctrine:migration:migrate --no-interaction"
    chdir: "{{ app_directory }}/docker"

# todo if first deployment create first user with command
